name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 2048
num_choices: 1

# a list of model to generate answers
model_list:
  - IlyaGusev_saiga_yandexgpt_8b
  - saiga_yandexgpt_8b_sft_m4_jf_train_full
  - saiga_yandexgpt_8b_smpo_m3_full
  - gemma-2-9b-it-AWQ
  - qwen2.5:7b-instruct-q4_K_M
  - mistral-nemo:12b-instruct-2407-q4_0
  - mistral-nemo:12b-instruct-2407-q4_K_M
  - qwen2.5:14b-instruct-q4_K_M
  - llama3:8b-instruct-q4_K_M
  - mistral:7b-instruct-v0.3-q4_K_M
  - gemma-2-9b-it
